### ISSUE TITLE
Error stat'ing config file

### ISSUE THREAD

**Issue by marbetschar** [franckverrot/git_fdw#10]
Feels like we are nearly there 👍 

Now `git_fdw` throws this error: `libgit2 returned error code -1: Error stat'ing config file '/root/.gitconfig'.`. I'm quite sure this is because of my setup, because I have a dedicated `git` user.

Is there a way to tell `git_fdw` which user it should use to query the repos?

**Comment by franckverrot** [comment]
> Feels like we are nearly there 👍

Ahah, thanks for pushing on this, looks like my own setup was pretty naive too.

> Now git_fdw throws this error: libgit2 returned error code -1: Error stat'ing config file '/root/.gitconfig'.

I'm wondering why it's looking at root's gitconfig if you're using a dedicated git user.  Have you cloned the repo as root?  Are yo usure it's really using that git user?

As to your question, no, it's gonna be run by whatever user postgresql is running as I believe.

**Comment by marbetschar** [comment]
@franckverrot I suspect this is due to the reason I'm running multiple services within the container using `supervisord`. So I guess that's why git_fdw probably wants to access root's gitconfig.

I need it to access /home/git/.gitconfig - simply symlinking it to /root/.gitconfig did not help unfortunately...

**Comment by franckverrot** [comment]
is your PG running as root?

**Comment by franckverrot** [comment]
Also, you pasted the details line, mind pasting the one starting with "Failed opening repository" ?

**Comment by marbetschar** [comment]
I configured `supervisord` to run `sshd`, `gitea` and `postgres`. Where `sshd` is running as `root`, `gitea` as `git` and `postgres` as `postgres`.

Here the full error I get:
```
ERROR:  Failed opening repository: '/app/data/gitea/repository/....git'
DETAIL:  libgit2 returned error code -1: Error stat'ing config file '/root/.gitconfig'
```

**Comment by franckverrot** [comment]
Thanks. What are the permissions on that directory? (/app/data/...)

Also, maybe doing on your server requires the FDW to set some search path? https://libgit2.github.com/libgit2/#HEAD/group/libgit2/git_libgit2_opts

I can't reproduce locally so I can't really find a solution on that one. Rugged seems to have found a way for a problem somewhat related to yours https://github.com/libgit2/rugged/pull/337/files

**Comment by marbetschar** [comment]
@franckverrot I think you're right. It seems like a path issue according to [this issue](https://github.com/libgit2/libgit2/issues/2122). Unfortunately I can't figure out how to set the search paths manually and to which path this should point to.

I tried it already [here](https://github.com/Mandelkind/git_fdw/commit/89895e6ae84df816bb7e0888aaf609b5a1947f4d), but it does not seem to work (at least it does not output anything).

Any idea?

**Comment by franckverrot** [comment]
How did you set GIT_SEARCH_PATH ?  If nothing gets printed out it means your process (PG in that case) can't read it

**Comment by marbetschar** [comment]
I've added the followin lines after `git_libgit2_init();` in the `gitBeginForeignScan` method ([full file here](https://github.com/Mandelkind/git_fdw/blob/89895e6ae84df816bb7e0888aaf609b5a1947f4d/git_fdw.c)):

```
const char* git_search_path = getenv("GIT_SEARCH_PATH");
  if(git_search_path != NULL){
    git_libgit2_opts(
      GIT_OPT_SET_SEARCH_PATH,
      GIT_CONFIG_LEVEL_GLOBAL,
      git_search_path
    );
  }

  ereport(ERROR,
            (errcode(ERRCODE_SYNTAX_ERROR),
             errmsg(git_search_path)));
  return;
```

And I've tried to set `GIT_SEARCH_PATH` to `/home/git` where the `.gitconfig` is stored. Don't know if this is the correct value for `GIT_SEARCH_PATH` though.

**Comment by marbetschar** [comment]
I was now able to output the set environment var; but it is `NULL`. [This code here](https://github.com/Mandelkind/git_fdw/blob/master/git_fdw.c#L282-L294) generates the following output:

```
ERROR: GIT_SEARCH_PATH
DETAIL: GIT_SEARCH_PATH: (null)
```

I'm pretty sure though the environment variable exists, since postgres is run using `supervisord` - where I set the following configuration:

```
[program:postgresql]
user=postgres
...
environment=GIT_SEARCH_PATH="/home/git"
```

Any idea how to further pin this down?

**Comment by marbetschar** [comment]
I'm running out of ideas.... Just tested setting the env var in my Docker file according to the [Docker documentation](https://docs.docker.com/docker-cloud/getting-started/deploy-app/6_define_environment_variables/) (`ENV GIT_SEARCH_PATH "/home/git"`). git_fdw is still returning `NULL`.

What I'm doing wrong? Does getting a custom env var work in your test environment?

**Comment by franckverrot** [comment]
I have no idea, mind sharing that Dockerfile?  If I can reproduce I could give a shot at fixing this.  I'm not familiar with supervisord so I'll have to dig a little.

Before digging too deep on that solution, can you confirm that calling `git_libgit2_opts` with `git_search_path` set to `/home/git` make it all work?

**Comment by marbetschar** [comment]
I can confirm that as soon as I'm setting `git_libgit2_opts` manually things start working:
https://github.com/Mandelkind/git_fdw/blob/6a39a2578881d890e0c69fc9e5ca539eee01e3c8/git_fdw.c#L284-L288

I've sent you the repo containing the Dockerfile etc. to you GitHub visible mail address.

**Comment by marbetschar** [comment]
Seems like its just a matter of figuring out how or where to set the env var so git_fdw (which is run by postgres which is run by supervisord which is run by docker) can get the value :confused:

**Comment by marbetschar** [comment]
Finally!!!! :tada: :tada: :tada: 
Adding the variable to the system environment of the docker container did the trick:

```
ENV GIT_SEARCH_PATH "/home/git"
echo "GIT_SEARCH_PATH=${GIT_SEARCH_PATH}" >> /etc/environment
```

Would you mind adding the following snippet to the official release?

```
  char* git_search_path = getenv("GIT_SEARCH_PATH");
  if(git_search_path != NULL){
    git_libgit2_opts(
      GIT_OPT_SET_SEARCH_PATH,
      GIT_CONFIG_LEVEL_GLOBAL,
      git_search_path
    );
  }
```

https://github.com/Mandelkind/git_fdw/blob/master/git_fdw.c#L282-L289

**Comment by franckverrot** [comment]
Oh that's great to hear.  I'll merge it with some tweaks, thanks for investigating.

**Comment by franckverrot** [comment]
Please tell me if it's fixed @marbetschar  :-)

**Comment by marbetschar** [comment]
Seems to work - thank you!! 🎉

Although I have no clue why and how it is now getting the value from the environment var - but I'm not familiar with these C stuff anyway 😝 

Do you mind creating a newly tagged version so I can get this as stable version in my Dockerfile instead of simply pointing to master?

**Comment by franckverrot** [comment]
Alright, it's done :-)

**Comment by franckverrot** [comment]
2.1.0

**Comment by franckverrot** [comment]
Oh, and I'm not using the environment variables anyways... soooo, maybe that was it ahah

**Comment by franckverrot** [comment]
("it" being: set the opts)
