### ISSUE TITLE
LoC changed

### ISSUE THREAD

**Issue by marbetschar** [franckverrot/git_fdw#5]
Any chance we can query the lines of code changed (added or removed) and maybe the diff of each commit?

**Comment by franckverrot** [comment]
Definitely possible, after all we're just using libgit2 :-)

Would you like to give it a try?  I can assist and review code.  Here's the [diff API explained][diff], I think it's all about getting enough data to run [`git_diff_stats`][diff_stats] as the result object can be used to extract [insertions][insertions] and [deletions][deletions].

For the diff itself, I'm pretty sure it's also in there, just a matter of deciphering that example (I've only use libgit2 a couple times for trivial matters like this FDW).

If you prefer not trying to add that feature, I might not get to it very quickly, depending on some other side projects and you know... work 😅 



[diff]: https://libgit2.github.com/libgit2/ex/HEAD/diff.html
[diff_stats]: https://libgit2.github.com/libgit2/#HEAD/type/git_diff_stats
[insertions]: https://libgit2.github.com/libgit2/#HEAD/group/diff/git_diff_stats_insertions
[deletions]: https://libgit2.github.com/libgit2/#HEAD/group/diff/git_diff_stats_deletions

**Comment by marbetschar** [comment]
@franckverrot thanks for the detailed infos. I might give it a try these days - however I never written anything in C before, so I'm not sure if I'm able to do it.

Any help on this would be greatly appreciated.

**Comment by marbetschar** [comment]
FWIW: I'm planning to setup a Gitea environment which is PostgreSQL backed, allowing for querying statistical data and maintains `git_fdw` automatically upon repo creation, update and deletion.
https://discourse.gitea.io/t/repository-create-update-delete-hooks/209

Will this work in terms of performance if I want to do live queries? Don't know how indexing is done in PostgreSQL <-> git_fdw <-> Git

**Comment by marbetschar** [comment]
Tried to setup the dev environment on my Mac; but got stuck with a `extension "git_fdw" has no installation script nor update path for version "1.0"` error - no clue why.

Installed PostgreSQL using `$: brew install postgresql` and added a database named `git`.

```
$: make
make: Nothing to be done for `all'.
$: make install
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/lib/postgresql'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/lib/postgresql'
/usr/bin/install -c -m 755  git_fdw.so '/usr/local/lib/postgresql/git_fdw.so'
/usr/bin/install -c -m 644 .//git_fdw.control '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 644 .//git_fdw--1.0.2.sql  '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 755  git_fdw.so '/usr/local/lib/postgresql/'
$: psql git
psql (10.2)
Type "help" for help.

git=# CREATE EXTENSION git_fdw;
ERROR:  extension "git_fdw" has no installation script nor update path for version "1.0"
```

**Comment by marbetschar** [comment]
Ok. Figured it out: `git_fdw.control` had `default_version` set to `1.0` where it should have been `1.0.2`

**Comment by franckverrot** [comment]
> Ok. Figured it out: git_fdw.control had default_version set to 1.0 where it should have been 1.0.2

Whoops, I'll make sure this repo works just as well as the one on [pgxn](pgxn.org).

> Will this work in terms of performance if I want to do live queries? Don't know how indexing is done in PostgreSQL <-> git_fdw <-> Git

That's a very good question.  A `select` just scans through all the git commits, there's no cache or other mechanism to speed things up.  So I'd probably only use the FDW to extract the last <X> commits, every now and then, building a stored database of commits in a real table incrementally.

**Comment by franckverrot** [comment]
> however I never written anything in C before, so I'm not sure if I'm able to do it.
> Any help on this would be greatly appreciated.

Sure thing.  I just noticed your repo and I think you got something going.

I think we should probably create another table for stats.  There's no way right now to do it in the configuration, so doing it your way (add stats in the same table) is fine for now, we'll refactor later.

Now you might wonder how to provide another table for stats purpose.  I believe we might be able to provide another option to the `create foreign table` statement, like

```sql
# CREATE FOREIGN TABLE
    rails_repository_stats (...   # <-- notice the _stats
    )
    SERVER git_fdw_server
    OPTIONS (
        path   '/home/franck/rails/.git',
        branch 'master',
        type 'statistics'  # <-- not sure about the name of the option nor the value, but you got the idea I hope
    );
```

So that the FDW knows what type of data to fetch and return.

HTH, tell me if that wasn't clear enough!  And thanks for giving it a try, it's great!

**Comment by marbetschar** [comment]
yeah, a configurable way is a good idea. Do you have any idea how we could add multiple Tuples per commit (one per path/file)? As far from what I've understood the code right now this is not possible without quite a refactor effort.

If there is no easy solution right now, I'd be fine with the three new columns - it's enough to kick things further on my end. That said, getting the pull request merged into the official version as soon as possible would be awesome!

**Comment by franckverrot** [comment]
> Do you have any idea how we could add multiple Tuples per commit (one per path/file)? As far from what I've understood the code right now this is not possible without quite a refactor effort.

No I don't think it's possible, but the configuration would make it possible for the FDW to choose whether it has to deal with the commit logs or the stats.

> If there is no easy solution right now, I'd be fine with the three new columns - it's enough to kick things further on my end. That said, getting the pull request merged into the official version as soon as possible would be awesome!

Let's take a look at the PR, I'm happy to merge it (with a tiny review) in if it works!

**Comment by franckverrot** [comment]
Moving discussion to the actual PR https://github.com/franckverrot/git_fdw/pull/6
