### ISSUE TITLE
Setup within a Docker container

### ISSUE THREAD

**Issue by marbetschar** [franckverrot/git_fdw#7]
I'm trying to install `git_fdw` within a Docker container which is connected to a PostgreSQL database.
For this, I've added the following lines in my `Dockerfile`:

```
RUN apt-get update && \
    apt-get install -y git libpq-dev pgxnclient libgit2-dev && \
    rm -rf /etc/ssh_host_* && \
    rm -r /var/cache/apt /var/lib/apt/lists && \
    pgxn install git_fdw
```

Unfortunately this fails with the following output:

```
INFO: best version: git_fdw 1.0.2
INFO: saving /tmp/tmp2Bkj3H/git_fdw-1.0.2.zip
INFO: unpacking: /tmp/tmp2Bkj3H/git_fdw-1.0.2.zip
INFO: building extension
Makefile:12: /usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk: No such fil
e or directory
ERROR: command returned 2: make PG_CONFIG=/usr/bin/pg_config all
make: *** No rule to make target '/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles
/pgxs.mk'.  Stop.
The command '/bin/sh -c apt-get update &&     apt-get install -y openssh-server
git libpq-dev pgxnclient libgit2-dev &&     rm -rf /etc/ssh_host_* &&     rm -r
/var/cache/apt /var/lib/apt/lists &&     pgxn install git_fdw' returned a non-ze
ro code: 1
Build failed
Build failed
ERROR App could not be built due to errors above [ ...\n
pm\node_modules\cloudron\src\helper.js:65:29 ]
```

Do you have any clue why?

**Comment by franckverrot** [comment]
So you can actually reproduce the steps from the [CI config](https://github.com/franckverrot/git_fdw/blob/master/.travis.yml).

Usually, I set up the container like this:

```
export PG_VERSION=10
docker build -f tests/Dockerfiles/$PG_VERSION -t my_git_fdw .
```

Then run the tests like this:

```
docker run my_git_fdw tests/run.sh $PG_VERSION
```

You could mount a volume to speed things up, depends on how long it takes to just recompile the last part of the [Dockerfile](https://github.com/franckverrot/git_fdw/blob/master/tests/Dockerfiles/10) (which does `make install`)

**Comment by franckverrot** [comment]
@marbetschar I'm closing this, don't hesitate to re-open or keep the convo going if it's still blurry.

Thanks again for your contribution!
