### ISSUE TITLE
[FIXED] Failed opening (bare) repository

### ISSUE THREAD

**Issue by marbetschar** [franckverrot/git_fdw#8]
I've setup a new server using Postgres 9.5 along with git_fdw compiled from master branch. Now I've tried to get the extension running but I receive the following error:

```
postgres=> SELECT * FROM test;
ERROR:  Failed opening repository: '/app/data/repository/test.git' -1
```

I even tried to set the permissions of the directories to 777, but I still receive the same error. FWIW: The path points to a bare repository - don't know if this makes any difference.

Any idea why this happens?

**Comment by franckverrot** [comment]
The way we read repositories can’t work with bare repositories I believe (https://github.com/franckverrot/git_fdw/blob/master/git_fdw.c#L295): we read refs directly to determine commit SHAs and then walk the repo.  There is another way that could be compatible with both bare and full repos though. I’m away from my computer so can’t look at it now, if you find it before me feel free to send a PR

**Comment by marbetschar** [comment]
I just tested this using a regular repository and receive the same error. This is within a docker container though, any idea how to debug this issue to get to the root cause?

**Comment by franckverrot** [comment]
You could build the container et then run bash into it.  You can then setup things manually (just like how we run things on CI.  I'll give it a shot soon

**Comment by franckverrot** [comment]
I actually just tried, and it's working fine (as it does on CI).

And I confirm that just running the CI script just works.  Make sure you install vim (you're not an emacs kinda person right? :trollface: ) beforehand (or via apt-get) so you can edit the setup script in the container.

**Comment by marbetschar** [comment]
I have no clue why my `git_fdw` instance still does not work. It insists throwing the `Failed opening repository: '/app/data/repository/test.git' -1` error.

I'm installing all the dependencies you have in your Dockerfile for Postgres v9.5:

```
ENV GIT_FDW_VERSION master
ENV POSTGRESQL_VERSION 9.5

RUN sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
	sudo apt-get install wget ca-certificates && \
	wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && \
	apt-get update && \
    apt-get install -y \
    	openssh-server \
    	build-essential \
    	flex bison \
    	git \
    	libc6-dev-i386 \
    	libpq-dev \
    	postgresql-${POSTGRESQL_VERSION} \
    	postgresql-server-dev-${POSTGRESQL_VERSION} \
    	libgit2-dev \
    	postgresql-${POSTGRESQL_VERSION}-cron \
    	pgxnclient && \
    rm -rf /etc/ssh_host_* && \
    rm -r /var/cache/apt /var/lib/apt/lists

RUN wget -P /tmp https://github.com/franckverrot/git_fdw/archive/${GIT_FDW_VERSION}.zip && \ 
	unzip /tmp/${GIT_FDW_VERSION}.zip -d /tmp && \
	cd /tmp/git_fdw-${GIT_FDW_VERSION} && \
	make install
```

Setting up the `postgres` database:

```
--- Set password for user postgres
ALTER USER postgres WITH PASSWORD '##POSTGRESQL_PASSWORD';

-- Create a root superuser for non-local connections (we could also use postgres superuser but it's usually local only)
CREATE USER root SUPERUSER;
ALTER USER root WITH PASSWORD '##POSTGRESQL_ROOT_PASSWORD';

-- https://wiki.postgresql.org/wiki/Shared_Database_Hosting
REVOKE ALL ON DATABASE template1 FROM public;
REVOKE ALL ON SCHEMA public FROM public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO root;

-- Create extensions
CREATE EXTENSION git_fdw;
CREATE SERVER git_fdw_server FOREIGN DATA WRAPPER git_fdw;
```

And finally adding the FOREIGN TABLE according to the docs, which leads to the error:

```
postgres=> SELECT * FROM test;
ERROR:  Failed opening repository: '/app/data/repository/test.git' -1
```

I'm a bit lost here, any help would be highly appreciated.

**Comment by franckverrot** [comment]
Is it still a bare repository?  If so, git_fdw isn't capable of opening them as it's looking at refs.

**Comment by marbetschar** [comment]
yeah, still bare. Any chance to get this running for bare and regular repos? Since I going to create the stats for hosted repos on the server side there aren't any regular repos at all :(

**Comment by franckverrot** [comment]
We might be able to do it.  In the mean time, I've just added a HINT section to the error message you'll get.  Do you mind telling me what it's saying now?

**Comment by franckverrot** [comment]
Good news, I found a way to make it work.  Bad news, I was working from /tmp this morning and got an unplanned hard restart... so .... i’ll do it again, it’s actually a no-brainer but changes a couple things in the config.

**Comment by franckverrot** [comment]
Alright, it's done: https://github.com/franckverrot/git_fdw/commit/5d4c7ce77c663718a9e356959a584a6ce694066d

Please tell me if it's all good on your end.

**Comment by marbetschar** [comment]
@franckverrot just checked out the latest master branch, it now fails to compile on my machine:

```
$: make && make install
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2   -I. -I./ -I/usr/local/Cellar/postgresql/10.2/include/server -I/usr/local/Cellar/postgresql/10.2/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2   -c -o git_fdw.o git_fdw.c
git_fdw.c:68:34: warning: incompatible pointer types assigning to 'GetForeignPlan_function' (aka 'struct ForeignScan *(*)(struct PlannerInfo *, struct RelOptInfo *, unsigned int,
      struct ForeignPath *, struct List *, struct List *, struct Plan *)') from 'ForeignScan *(PlannerInfo *, RelOptInfo *, Oid, ForeignPath *, List *, List *)' (aka 'struct
      ForeignScan *(struct PlannerInfo *, struct RelOptInfo *, unsigned int, struct ForeignPath *, struct List *, struct List *)') [-Wincompatible-pointer-types]
  fdwroutine->GetForeignPlan     = gitGetForeignPlan;
                                 ^ ~~~~~~~~~~~~~~~~~
git_fdw.c:273:18: warning: suggest braces around initialization of subobject [-Wmissing-braces]
  git_oid oid = {0};
                 ^
                 {}
git_fdw.c:311:77: error: too few arguments to function call, expected 5, have 4
    error = git_remote_connect(remote, GIT_DIRECTION_FETCH, &callbacks, NULL);
            ~~~~~~~~~~~~~~~~~~                                              ^
/usr/local/include/git2/remote.h:247:1: note: 'git_remote_connect' declared here
GIT_EXTERN(int) git_remote_connect(git_remote *remote, git_direction direction, const git_remote_callbacks *callbacks, const git_proxy_options *proxy_opts, const git_strarra...
^
/usr/local/include/git2/common.h:42:27: note: expanded from macro 'GIT_EXTERN'
# define GIT_EXTERN(type) extern \
                          ^
2 warnings and 1 error generated.
make: *** [git_fdw.o] Error 1
```

**Comment by marbetschar** [comment]
@franckverrot created a [pull request](https://github.com/franckverrot/git_fdw/pull/9) which fixes the issue. I can confirm that querying bare repos is now working. Awesome work man! 🎉
